import ExcelJS from "exceljs";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export interface ExportDataPayload {
  title: string;
  subtitle?: string;
  filename: string;
  sheetName?: string;
  headers: string[];
  rows: (string | number)[][];
  summary?: { label: string; value: string | number }[];
  companyName?: string;
  generatedBy?: string;
}

/**
 * Export structured dataset to native Microsoft Excel (.xlsx) workbook with styling
 */
export async function exportToExcel(payload: ExportDataPayload) {
  const {
    title,
    subtitle = "Financial Management Enterprise Report",
    filename,
    sheetName = "Report",
    headers,
    rows,
    summary,
    companyName = "HORECA Hospitality & Asset Enterprise",
    generatedBy = "System User"
  } = payload;

  const workbook = new ExcelJS.Workbook();
  workbook.creator = "HORECA Financial Suite";
  workbook.created = new Date();

  const worksheet = workbook.addWorksheet(sheetName.substring(0, 31));

  // Add Company Header
  worksheet.mergeCells("A1", `${String.fromCharCode(64 + Math.max(headers.length, 4))}1`);
  const headerCell = worksheet.getCell("A1");
  headerCell.value = companyName.toUpperCase();
  headerCell.font = { name: "Arial", size: 14, bold: true, color: { argb: "FFFFFFFF" } };
  headerCell.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF1A1D21" }
  };
  headerCell.alignment = { horizontal: "center", vertical: "middle" };
  worksheet.getRow(1).height = 28;

  // Add Title and Subtitle
  worksheet.mergeCells("A2", `${String.fromCharCode(64 + Math.max(headers.length, 4))}2`);
  const titleCell = worksheet.getCell("A2");
  titleCell.value = `${title} — ${subtitle}`;
  titleCell.font = { name: "Arial", size: 11, bold: true, color: { argb: "FF1A1D21" } };
  titleCell.alignment = { horizontal: "left", vertical: "middle" };
  worksheet.getRow(2).height = 20;

  // Add Metadata Row
  worksheet.mergeCells("A3", `${String.fromCharCode(64 + Math.max(headers.length, 4))}3`);
  const metaCell = worksheet.getCell("A3");
  metaCell.value = `Exported: ${new Date().toLocaleString("en-PH")} | Generated by: ${generatedBy} | Confidential`;
  metaCell.font = { name: "Arial", size: 9, italic: true, color: { argb: "FF5C636F" } };
  metaCell.alignment = { horizontal: "left", vertical: "middle" };
  worksheet.getRow(3).height = 18;

  worksheet.addRow([]); // Blank line

  // Add Table Headers
  const headerRow = worksheet.addRow(headers);
  headerRow.height = 24;
  headerRow.eachCell((cell) => {
    cell.font = { name: "Arial", size: 10, bold: true, color: { argb: "FFFFFFFF" } };
    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF2B3037" }
    };
    cell.alignment = { horizontal: "center", vertical: "middle" };
    cell.border = {
      top: { style: "thin", color: { argb: "FFDFE1DB" } },
      left: { style: "thin", color: { argb: "FFDFE1DB" } },
      bottom: { style: "medium", color: { argb: "FF1A1D21" } },
      right: { style: "thin", color: { argb: "FFDFE1DB" } }
    };
  });

  // Add Data Rows
  rows.forEach((rowData, idx) => {
    const row = worksheet.addRow(rowData);
    row.height = 20;
    const isEven = idx % 2 === 0;
    row.eachCell((cell, colNumber) => {
      cell.font = { name: "Arial", size: 9.5 };
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: isEven ? "FFFFFFFF" : "FFF8F8F6" }
      };
      cell.border = {
        top: { style: "thin", color: { argb: "FFE5E7EB" } },
        left: { style: "thin", color: { argb: "FFE5E7EB" } },
        bottom: { style: "thin", color: { argb: "FFE5E7EB" } },
        right: { style: "thin", color: { argb: "FFE5E7EB" } }
      };

      // Auto format numbers vs text
      if (typeof cell.value === "number") {
        cell.alignment = { horizontal: "right", vertical: "middle" };
        if (headers[colNumber - 1]?.toLowerCase().includes("amount") ||
            headers[colNumber - 1]?.toLowerCase().includes("debit") ||
            headers[colNumber - 1]?.toLowerCase().includes("credit") ||
            headers[colNumber - 1]?.toLowerCase().includes("balance") ||
            headers[colNumber - 1]?.toLowerCase().includes("tax") ||
            headers[colNumber - 1]?.toLowerCase().includes("budget") ||
            headers[colNumber - 1]?.toLowerCase().includes("spent")) {
          cell.numFmt = "₱#,##0.00";
        }
      } else {
        cell.alignment = { horizontal: "left", vertical: "middle" };
      }
    });
  });

  // Add Summary KPI Section if available
  if (summary && summary.length > 0) {
    worksheet.addRow([]);
    const sumHeaderRow = worksheet.addRow(["EXECUTIVE SUMMARY & KPI TOTALS", ""]);
    sumHeaderRow.getCell(1).font = { name: "Arial", size: 10, bold: true, color: { argb: "FFB53A1E" } };
    summary.forEach((item) => {
      const sumRow = worksheet.addRow([item.label, item.value]);
      sumRow.getCell(1).font = { name: "Arial", size: 9.5, bold: true };
      sumRow.getCell(2).font = { name: "Arial", size: 9.5, bold: true };
      if (typeof item.value === "number") {
        sumRow.getCell(2).numFmt = "₱#,##0.00";
      }
    });
  }

  // Auto-fit column widths
  worksheet.columns.forEach((column) => {
    let maxLength = 12;
    column.eachCell?.({ includeEmpty: true }, (cell) => {
      const cellValue = cell.value ? cell.value.toString() : "";
      if (cellValue.length > maxLength && cellValue.length < 50) {
        maxLength = cellValue.length;
      }
    });
    column.width = Math.min(maxLength + 4, 38);
  });

  // Generate buffer and trigger browser download
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${filename}_${new Date().toISOString().split("T")[0]}.xlsx`;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

/**
 * Export structured dataset to professional PDF document using jsPDF + autoTable
 */
export function exportToPDF(payload: ExportDataPayload) {
  const {
    title,
    subtitle = "Financial Management Enterprise Report",
    filename,
    headers,
    rows,
    summary,
    companyName = "HORECA HOSPITALITY & ASSET ENTERPRISE",
    generatedBy = "System User"
  } = payload;

  const doc = new jsPDF({
    orientation: headers.length > 6 ? "landscape" : "portrait",
    unit: "mm",
    format: "a4"
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Top Corporate Banner
  doc.setFillColor(26, 29, 33); // #1A1D21
  doc.rect(0, 0, pageWidth, 22, "F");

  // Company Name
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(companyName, 14, 10);

  // System Badge
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(255, 106, 61); // #FF6A3D
  doc.text("CORE FINANCIAL SUITE & ERP ENGINE", 14, 16);

  // Document Title
  doc.setTextColor(26, 29, 33);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(title, 14, 30);

  // Subtitle & Metadata
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(92, 99, 111); // #5C636F
  doc.text(`${subtitle} | Generated: ${new Date().toLocaleString("en-PH")} | User: ${generatedBy}`, 14, 36);

  // Render Table
  autoTable(doc, {
    startY: 41,
    head: [headers],
    body: rows.map((r) =>
      r.map((val) => {
        if (typeof val === "number") {
          return new Intl.NumberFormat("en-PH", {
            style: "currency",
            currency: "PHP"
          }).format(val);
        }
        return String(val ?? "");
      })
    ),
    theme: "striped",
    headStyles: {
      fillColor: [37, 42, 49],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8.5,
      halign: "left"
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [26, 29, 33],
      lineColor: [223, 225, 219]
    },
    alternateRowStyles: {
      fillColor: [246, 246, 243]
    },
    styles: {
      overflow: "linebreak",
      cellPadding: 2.5
    },
    margin: { left: 14, right: 14, bottom: 20 },
    didDrawPage: (data) => {
      // Footer with page numbering
      const str = `Page ${doc.getNumberOfPages()} | Confidential HORECA ERP Document`;
      doc.setFontSize(8);
      doc.setTextColor(140, 145, 155);
      doc.text(str, 14, pageHeight - 8);
    }
  });

  // Summary box at bottom if available
  if (summary && summary.length > 0) {
    const finalY = (doc as any).lastAutoTable.finalY + 8;
    if (finalY < pageHeight - 30) {
      doc.setFillColor(241, 241, 237);
      doc.setDrawColor(223, 225, 219);
      doc.roundedRect(14, finalY, pageWidth - 28, 6 + summary.length * 6, 2, 2, "FD");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(181, 58, 30);
      doc.text("EXECUTIVE FINANCIAL SUMMARY", 18, finalY + 5);

      summary.forEach((item, index) => {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8.5);
        doc.setTextColor(26, 29, 33);
        doc.text(`${item.label}:`, 18, finalY + 11 + index * 5.5);

        doc.setFont("helvetica", "normal");
        const formattedVal = typeof item.value === "number"
          ? new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(item.value)
          : String(item.value);
        doc.text(formattedVal, 80, finalY + 11 + index * 5.5);
      });
    }
  }

  // Trigger download
  doc.save(`${filename}_${new Date().toISOString().split("T")[0]}.pdf`);
}
